name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build site
        run: deno task build


      - name: create file list
        id: files_list
        run: |
          echo "files=$(find _site -name '*.html' | grep -v 404 | grep -v index)" > $GITHUB_OUTPUT

      - name: Create HTML with all pages
        uses: docker://pandoc/latex:2.9
        with:
          args: --output=all.html _site/index.html ${{ steps.files_list.outputs.files }}

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: HTML to PDF converter
        uses: ferdinandkeller/html-to-pdf-action@v1
        with:
          source-path: 'all.html'
          destination-path: '_site/all.pdf'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
